# Pip3
## 1 Linux使用时异常
### 1.1 使用`python3 -m pip`
Linux上使用pip3(pip3 install xxx)出现错误：
```Python
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
```
解决方法：

不使用原命令调用，改用(sudo) python3 -m pip install xxx

# Amendant Record
1. 180617 Add #1